apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/host/directory"  # Ruta en el host para almacenar datos persistentes

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        args:
        - server
        - /data --console-address :9090
        volumeMounts:
        - name: minio-storage
          mountPath: /data
        env:
        - name: MINIO_ACCESS_KEY
          value: minioUserLocal123
        - name: MINIO_SECRET_KEY
          value: p4ssw0rd#

      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc
