apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: msc-dev-mysql-pv-claim
  
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  
  name: msc-dev-mysql-deployment
spec:
  selector:
    matchLabels:
      app: msc-dev-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: msc-dev-mysql
    spec:
      containers:
      - name: msc-dev-mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "vifa9510"
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: msc-dev-mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: msc-dev-mysql-service
  
spec:
  type: NodePort
  selector:
    app: msc-dev-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
